export enum Events {
	Ready = 'ready',
	Debug = 'debug',
	ApiRequest = 'apiRequest',
	ApiResponse = 'apiResponse',
	RateLimited = 'rateLimited',
	Raw = 'raw',
	Disconnect = 'disconnect',
	Error = 'error',
	DeviceAdd = 'deviceAdd',
	DeviceUpdate = 'deviceUpdate',
	DeviceDelete = 'deviceDelete',
	LightAdd = 'lightAdd',
	LightUpdate = 'lightUpdate',
	LightDelete = 'lightDelete',
	GroupedLightAdd = 'groupedLightAdd',
	GroupedLightUpdate = 'groupedLightUpdate',
	GroupedLightDelete = 'groupedLightDelete',
	RoomAdd = 'roomAdd',
	RoomUpdate = 'roomUpdate',
	RoomDelete = 'roomDelete',
	ZoneAdd = 'zoneAdd',
	ZoneUpdate = 'zoneUpdate',
	ZoneDelete = 'zoneDelete',
	SceneAdd = 'sceneAdd',
	SceneUpdate = 'sceneUpdate',
	SceneDelete = 'sceneDelete',
}
