export enum APIResourceType {
	Device = 'device',
	BridgeHome = 'bridge_home',
	Room = 'room',
	Zone = 'zone',
	Light = 'light',
	Button = 'button',
	Temperature = 'temperature',
	LightLevel = 'light_level',
	Motion = 'motion',
	Entertainment = 'entertainment',
	GroupedLight = 'grouped_light',
	DevicePower = 'device_power',
	ZigbeeConnectivity = 'zigbee_connectivity',
	ZgpConnectivity = 'zgp_connectivity',
	ZigbeeDeviceDiscovery = 'zigbee_device_discovery',
	Bridge = 'bridge',
	Homekit = 'homekit',
	Scene = 'scene',
	EntertainmentConfiguration = 'entertainment_configuration',
	PublicImage = 'public_image',
	BehaviourScript = 'behaviour_script',
	BehaviourInstance = 'behaviour_instance',
	Geofence = 'geofence',
	GeofenceClient = 'geofence_client',
	Geolocation = 'geolocation',
}

export type APIResource<T extends APIResourceType = APIResourceType> = { id: string; type: T } & Record<string, any>;

export interface APIResourceIdentifier<T extends APIResourceType = APIResourceType> {
	rid: string;
	rtype: T;
}

export enum APIArcheType {
	Unknown = 'unknown_archetype',
	ClassicBulb = 'classic_bulb',
	SultanBulb = 'sultan_bulb',
	FloodBulb = 'flood_bulb',
	SpotBulb = 'spot_bulb',
	CandleBulb = 'candle_bulb',
	LusterBulb = 'luster_bulb',
	PendantRound = 'pendant_round',
	PendantLong = 'pendant_long',
	CeilingRound = 'ceiling_round',
	CeilingSquare = 'ceiling_square',
	FloorShade = 'floor_shade',
	FloorLantern = 'floor_lantern',
	TableShade = 'table_shade',
	RecessedCeiling = 'recessed_ceiling',
	RecessedFloor = 'recessed_floor',
	SingleSpot = 'single_spot',
	DoubleSpot = 'double_spot',
	TableWash = 'table_wash',
	WallLantern = 'wall_lantern',
	WallShade = 'wall_shade',
	FlexibleLamp = 'flexible_lamp',
	GroundSpot = 'ground_spot',
	WallSpot = 'wall_spot',
	Plug = 'plug',
	HueGo = 'hue_go',
	HueLightstrip = 'hue_lightstrip',
	HueIris = 'hue_iris',
	HueBloom = 'hue_bloom',
	Bollard = 'bollard',
	WallWasher = 'wall_washer',
	HuePlay = 'hue_play',
	VintageBulb = 'vintage_bulb',
	VintageCandleBulb = 'vintage_candle_bulb',
	EllipseBulb = 'ellipse_bulb',
	TriangleBulb = 'triangle_bulb',
	SmallGlobeBulb = 'small_globe_bulb',
	LargeGlobeBulb = 'large_globe_bulb',
	EdisonBulb = 'edison_bulb',
	ChristmasTree = 'christmas_tree',
	StringLight = 'string_light',
	HueCentris = 'hue_centris',
	HueLightstripTV = 'hue_lightstrip_tv',
	HueLightStripPC = 'hue_lightstrip_pc',
	HueTube = 'hue_tube',
	HueSigne = 'hue_signe',
	PendantSpot = 'pendant_spot',
	CeilingHorizontal = 'ceiling_horizontal',
	CeilingTube = 'ceiling_tube',
	LivingRoom = 'living_room',
	Kitchen = 'kitchen',
	Dining = 'dining',
	Bedroom = 'bedroom',
	KidsBedroom = 'kids_bedroom',
	Bathroom = 'bathroom',
	Nursery = 'nursery',
	Recreation = 'recreation',
	Office = 'office',
	Gym = 'gym',
	Hallway = 'hallway',
	Toilet = 'toilet',
	FrontDoor = 'front_door',
	Garage = 'garage',
	Terrace = 'terrace',
	Garden = 'garden',
	Driveway = 'driveway',
	Carport = 'carport',
	Home = 'home',
	Downstairs = 'downstairs',
	Upstairs = 'upstairs',
	TopFloor = 'top_floor',
	Attic = 'attic',
	GuestRoom = 'guest_room',
	Staircase = 'staircase',
	Lounge = 'lounge',
	ManCave = 'man_cave',
	Computer = 'computer',
	Studio = 'studio',
	Music = 'music',
	TV = 'tv',
	Reading = 'reading',
	Closet = 'closet',
	Storage = 'storage',
	LaundryRoom = 'laundry_room',
	Balcony = 'balcony',
	Porch = 'porch',
	Barbecue = 'barbecue',
	Pool = 'pool',
	Other = 'other',
}

export enum APIDeltaAction {
	Up = 'up',
	Stop = 'stop',
	Down = 'down',
}
